gpus_to_simulate : 128
num_workers : 6
conv_feature_layers : [(512,10,5)]+[(512,3,2)]*4+[(512,2,2)]*2
final_dim : 768
latent_vars : 320
latent_groups : 2
latent_temp : (2.0,0.1,0.999995)
optimizer : adam
adam_betas : (0.9,0.98)
adam_eps : 1e-06
lr_scheduler : polynomial_decay
total_num_update : 600000
lr : 0.0003
warmup_updates : 32000

mask:
  selection : static
  other : 0
  length : 10
  prob : 0.65

dropout_input : 0.1
dropout_features : 0.1
feature_grad_mult : 0.03
loss_weights : [0.1,10]
conv_pos : 128
conv_pos_groups : 16
num_negatives : 100
cross_sample_negatives : 0
max_sample_size : 320000
min_sample_size : 32000
dropout : 0.0
attention_dropout : 0.1
weight_decay : 0.01
max_tokens : 1200000
max_update : 600000
ddp_backend : no_c10d

# variables not present in pretraining_base.yaml
encoder:
  layerdrop : 0.0
  layers : 24
  embed_dim : 1024
  ffn_embed_dim : 4096
  attention_heads : 16
